#!/bin/sh
echo "automount ...";

rm -rf /var/lib/docker
mkdir /var/lib/docker
mkdir /host
mount -t 9p -o version=9p2000.L -o trans=virtio -o cache=mmap -o msize=512000 docker /var/lib/docker
mount -t 9p -o version=9p2000.L -o trans=virtio -o cache=mmap -o msize=512000 mnt /host

if [ ! -f /var/lib/docker/storage.img ]; then
  /usr/local/bin/truncate -s 1T /var/lib/docker/storage.img
  mkfs.ext4 /var/lib/docker/storage.img
fi

mount -o loop /var/lib/docker/storage.img /var/lib/docker

echo "automount over."
