#!/bin/sh
echo "automount ...";

rm -rf /var/lib/docker
mkdir /var/lib/docker
mkdir /host
mount -t 9p -o version=9p2000.L -o trans=virtio -o cache=mmap docker /var/lib/docker
mount -t 9p -o version=9p2000.L -o trans=virtio -o cache=mmap mnt /host

echo "automount over."
